#ifndef LIBCORK_CONFIG_VERSION_H
#define LIBCORK_CONFIG_VERSION_H

/* Version information */
#define CORK_CONFIG_VERSION_MAJOR    1
#define CORK_CONFIG_VERSION_MINOR    0
#define CORK_CONFIG_VERSION_PATCH    0
#define CORK_CONFIG_VERSION_STRING   "1.0.0--rc3"
#define CORK_CONFIG_REVISION         "a89596ce224438c136ef0336a81c51262cad9cd3"

#define CORK_VERSION_MAJOR    CORK_CONFIG_VERSION_MAJOR
#define CORK_VERSION_MINOR    CORK_CONFIG_VERSION_MINOR
#define CORK_VERSION_PATCH    CORK_CONFIG_VERSION_PATCH

#endif /* LIBCORK_CONFIG_VERSION_H */ 