/* an_config.h for iOS/macOS compilation */
#define HAVE_ARPA_INET_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_MEMORY_H 1
#define HAVE_FCNTL_H 1
#define HAVE_ERRNO_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_PTHREAD 1
#define HAVE_SOCKLEN_T 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETHOSTBYNAME 1
#define WRAP_GETHOSTBYNAME 1
#define HAVE_INET_NTOA 1
#define HAVE_INET_ATON 1
#define HAVE_MEMSET 1
#define HAVE_MEMMOVE 1
#define HAVE_SOCKET 1
#define HAVE_STRCHR 1
#define HAVE_STRDUP 1
#define HAVE_STRERROR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define STDC_HEADERS 1
#define TIME_WITH_SYS_TIME 1
#define RETSIGTYPE void
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_VOID_P 8
#define PACKAGE "antinat"
#define VERSION "0.91"
/* OpenSSL支持 */
#define HAVE_OPENSSL 1
#define HAVE_LIBSSL 1
#define HAVE_LIBCRYPTO 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_OPENSSL_ERR_H 1
#define HAVE_OPENSSL_CRYPTO_H 1
#define HAVE_OPENSSL_RSA_H 1
#define HAVE_OPENSSL_X509_H 1
#define HAVE_OPENSSL_PEM_H 1
/* XML支持 */
#define HAVE_EXPAT 1
#define HAVE_LIBEXPAT 1
#define XML_DTD 1
#define XML_NS 1
