#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define MBEDTLS_PLATFORM_C
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_AES_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CIPHER_MODE_GCM
#define MBEDTLS_CIPHER_MODE_CFB
#define MBEDTLS_GCM_C
#define MBEDTLS_MD5_C

#include "check_config.h"

#endif /* MBEDTLS_CONFIG_H */
